# Generated by Django 5.2.7 on 2025-10-21 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('authorname', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/')),
                ('ads', models.ImageField(blank=True, null=True, upload_to='ads/')),
            ],
        ),
    ]
